### PR TITLE
Frontend refactors

### LINKED ISSUE #3: not working when post edited
Fancybox doesn't work when post is edited.
The fancybox needs page to be reloaded for it to work

### PR DESCRIPTION
**Pull request by YUCLing**
This PR made some changes to the frontend, listed as follows:
- Move to TypeScript
- Use `refreshContent` for initialization (fixes #3)
- Use DOM-based initialization check, so initialization after `refreshContent` is possible (won't cause regression of #11 in theory)
- Fix the build of CSS on Windows
- ~Fix Fancybox slide and gallery carousel's syncing~ Now it works out of box with Fancybox
- Remove duplicated Fancybox style imported in JavaScript
- Remove ~duplicated~ Fancybox's carousel event registration (it's completely useless now)

~I think some places can be deleted as they seem to be redundant to me, but I'm not sure of the back story that makes them there. So I left them untouched.~

Although I've tested it and it all seems fine and backward compatible, I would like some double-quality checks and feedback from you.

### CODE REVIEW

**Comment by iamdarkle** [comment]
Hi, thanks for the time and effort on this, I'm going to review it ASAP and test it locally. 

> I think some places can be deleted as they seem to be redundant to me, but I'm not sure of the back story that makes them there. So I left them untouched.

That's quite possible, did you refer to the syncing part or something else?

**Comment by YUCLing** [comment]
> That's quite possible, did you refer to the syncing part or something else?

Yep, forgot to remove this part while editing.

**Comment by iamdarkle** [comment]
I've been testing it, and it works great. I really like the improvements you've made.

During the testing, I actually found an issue, but I'm sure it has nothing to do with your code. I checked, and it was already happening in the current version. If there are two galleries in the same post, the sync/index goes a bit crazy (https://github.com/iamdarkle/fancybox/issues/15).

If you want, I can release a version with your changes now, or if you don't mind waiting a bit, I can try to fix this issue and include it as well.

**Comment by YUCLing** [comment]
> If there are two galleries in the same post, the sync/index goes a bit crazy

Hmm, my test post contains two galleries and two individual images and I didn't encounter this issue. Is that because my galleries contain only two images?

> I can try to fix this issue and include it as well.

If you'd like to, I got no issue with it. 😃

**Comment by iamdarkle** [comment]
Oh sorry, you were absolutely right, I wrote that right after trying to compare the multiple galleries case with the previous version, but cache played a trick on me. The error is actually in the current version, and this fixes it!

I took the chance to add lazy loading, and IMO everything looks good, so I'm going to tag the new version (including your other PR). If anything comes up, don't hesitate to open an issue, and I'll try to help. Thanks! 🙂

**Pull request merged**
